version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/workspace/Yukino
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
        name: Install dependencies
        command: yarn install
      - save_cache:
        key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - ~/workspace/Yukino/node_modules
      - persist_to_workspace:
        root: .
        paths:
          - .
  test:
    working_directory: ~/workspace/Yukino
    - attach_workspace:
      at: ~/workspace/Yukino
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
        name: Linting
        command: yarn run lint
      - run:
        name: Compile
        command: yarn run compile:test

workflows:
  version: 2
  nodejs_tests:
    jobs:
      - build
      - test:
        requires:
          - build
